// <auto-generated />
namespace Spark.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class update_project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_project));
        
        string IMigrationMetadata.Id
        {
            get { return "202104272250405_update_project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
